### ISSUE TITLE
rewrite or fork?

### ISSUE THREAD

**Issue by mathieujobin** [jgottula/WinBtrfs#1]
opening this issue only for the discussion.

this project seems to be a rewrite of btrfs for windows.

wouldn't it be _easier_ to fork btrfs linux kernel code and use pre-compiler condition to remove the linux-only parts and add the windows heavy lifting?

maybe that's what you are doing and I did not see it.. sorry if this is the case.

perhaps the readme should explain the general strategy ? how would this project be able to keep up with btrfs features in the future?

**Comment by jgottula** [comment]
Hi,

This project is basically dead; I haven't touched it in a couple of years, the code's a bit of a mess, and it never got very far in terms of actual functionality or performance. But I thought I would address your question anyway, since it's a reasonable thing to ask.

I wrote this project as a separate implementation (rewrite) of Btrfs because it was relatively easy to do a basic userspace driver that could at least read data off a Btrfs volume from Windows. Part of the reason I started the project was that I wanted to learn how Btrfs worked, and rewriting it based on the documentation was beneficial to me in that way.

While the _cleanest_ solution would be to port the official Btrfs implementation to a Windows kernel mode driver (as it would then exactly match all of the features in the Linux version), I would hesitate to call it the _easiest_ way, for a couple of reasons:
1. There is only one working implementation of Btrfs in existence, and it is deeply integrated into Linux and uses features of the Linux kernel and its subsystems heavily. Therefore, porting the existing driver would require rewriting/wrapping all of those parts that interact with the operating system (memory allocation, the block layer, caching, etc.). This is _very nontrivial_, as filesystems are deeply entangled in the operating system for performance reasons. The Btrfs filesystem is part of the Linux kernel source tree; removing all of the dependencies on Linux would be a daunting task indeed. (For example, look at the list of #include's in [this file](https://github.com/torvalds/linux/blob/master/fs/btrfs/inode.c).)
   To get an idea of the amount of work this would entail, look at the [ZFS on Linux project](http://www.zfsonlinux.org). Brian Behlendorf, who has been working on the project for over five years and currently does this as his job, wrote the [Solaris Porting Layer](https://github.com/behlendorf/spl), a Linux kernel module that translates Solaris-specific kernel interfaces into their Linux equivalents (since ZFS came from Solaris originally). That effort has taken an _immense_ amount of work just to get to the point of stability; then, consider that Solaris and Linux are much more similar to each other than Linux and Windows are, so to make an equivalent "porting layer" for Linux to Windows would be very difficult indeed.
2. Useful documentation on how to write Windows kernel-mode filesystem drivers is hard to come by. I am aware of only [one book on the topic](http://www.amazon.com/Windows-File-System-Internals-Developers/dp/1565922492), which was written in 1997. (I own this book and have read most of it.) The way Windows filesystem drivers work probably hasn't changed much in the past 16 years, but it's hard to know for sure. Because people very rarely write native filesystem drivers for Windows, there is little online documentation on the topic, aside from [this third-party website](http://www.osronline.com/section.cfm?section=20), and even then, most of the information concerns filter drivers, which isn't relevant. Example code is hard to come by as well.

So, that's why I never got around to porting the official Btrfs driver to Windows, or even doing my own rewrite as a Windows kernel driver. It's certainly _possible_ to do, in theory, but it would take a ton of work and I've personally lost the time and interest that I had when I started this project.

Thanks for asking.

**Comment by Soukyuu** [comment]
I realize it's an old issue (and a dead project), but I think [dokan](https://code.google.com/p/dokan/) could possibly help in this case. I know Paragon uses it for their ext4 support for windows.

**Comment by Soukyuu** [comment]
Or rather, since dokan seems to be unmaintained, [dokany](https://github.com/dokan-dev/dokany)

**Comment by mathieujobin** [comment]
thanks all
